global:
  scrape_interval:     15s
  evaluation_interval: 15s

  external_labels:
    availability_zone: "$${SELF_AVAILABILITY_ZONE}"
    replica: "${instance}"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['localhost:9090']
