---
region: "eu-west-2"
component: "thanos"

private_network_cidr: "10.0.0.0/16"

state_bucket_name: "infrablocks-%{hiera('component')}-%{deployment_identifier}"
secrets_bucket_name: "%{hiera('state_bucket_name')}"

prometheus_storage_bucket_name: "infrablocks-%{hiera('component')}-%{deployment_identifier}-%{hiera('instance')}-storage"
prometheus_storage_bucket_region: "%{hiera('region')}"

domain_state_bucket_region: "%{hiera('region')}"
domain_state_bucket_name: "%{hiera('state_bucket_name')}"
domain_state_bucket_is_encrypted: "true"
domain_state_key: "domain/deployments/%{deployment_identifier}.tfstate"

certificate_state_bucket_region: "%{hiera('region')}"
certificate_state_bucket_name: "%{hiera('state_bucket_name')}"
certificate_state_bucket_is_encrypted: "true"
certificate_state_key: "certificate/deployments/%{deployment_identifier}.tfstate"

network_state_bucket_region: "%{hiera('region')}"
network_state_bucket_name: "%{hiera('state_bucket_name')}"
network_state_bucket_is_encrypted: "true"
network_state_key: "network/deployments/%{deployment_identifier}.tfstate"

cluster_state_bucket_region: "%{hiera('region')}"
cluster_state_bucket_name: "%{hiera('state_bucket_name')}"
cluster_state_bucket_is_encrypted: "true"
cluster_state_key: "cluster/deployments/%{deployment_identifier}.tfstate"

registry_state_bucket_region: "%{hiera('region')}"
registry_state_bucket_name: "%{hiera('state_bucket_name')}"
registry_state_bucket_is_encrypted: "true"
registry_state_key: "registry/deployments/%{deployment_identifier}.tfstate"

prometheus_state_bucket_region: "%{hiera('region')}"
prometheus_state_bucket_name: "%{hiera('state_bucket_name')}"
prometheus_state_bucket_is_encrypted: "true"
prometheus_state_key: "prometheus/deployments/%{hiera('instance')}.tfstate"

thanos_state_bucket_region: "%{hiera('region')}"
thanos_state_bucket_name: "%{hiera('state_bucket_name')}"
thanos_state_bucket_is_encrypted: "true"
thanos_state_key: "thanos/deployments/%{deployment_identifier}.tfstate"
