---
vars:
  region: "%{hiera('region')}"
  component: "%{hiera('component')}"
  deployment_identifier: "%{deployment_identifier}"

  domain_name: "%{hiera('domain_name')}"

  service_desired_count: 3

  secrets_bucket_name: "%{hiera('secrets_bucket_name')}"

  prometheus_image: "infrablocks/prometheus-aws:0.3.0"
  prometheus_service_container_port: "9090"
  prometheus_service_host_port: "9090"
  prometheus_service_lb_port: "9090"
  prometheus_storage_location: "/var/opt/prometheus"
  prometheus_allow_cidrs:
    - "0.0.0.0/0"

  domain_state_bucket_region: "%{hiera('domain_state_bucket_region')}"
  domain_state_bucket_name: "%{hiera('domain_state_bucket_name')}"
  domain_state_bucket_is_encrypted: "%{hiera('domain_state_bucket_is_encrypted')}"
  domain_state_key: "%{hiera('domain_state_key')}"

  network_state_bucket_region: "%{hiera('network_state_bucket_region')}"
  network_state_bucket_name: "%{hiera('network_state_bucket_name')}"
  network_state_bucket_is_encrypted: "%{hiera('network_state_bucket_is_encrypted')}"
  network_state_key: "%{hiera('network_state_key')}"

  cluster_state_bucket_region: "%{hiera('cluster_state_bucket_region')}"
  cluster_state_bucket_name: "%{hiera('cluster_state_bucket_name')}"
  cluster_state_bucket_is_encrypted: "%{hiera('cluster_state_bucket_is_encrypted')}"
  cluster_state_key: "%{hiera('cluster_state_key')}"

backend_config:
  region: "%{hiera('prometheus_state_bucket_region')}"
  bucket: "%{hiera('prometheus_state_bucket_name')}"
  encrypt: "%{hiera('prometheus_state_bucket_is_encrypted')}"
  key: "%{hiera('prometheus_state_key')}"
