---
vars:
  region: "%{hiera('region')}"
  component: "%{hiera('component')}"
  deployment_identifier: "%{deployment_identifier}"

  domain_name: "%{hiera('domain_name')}"

  prometheus_service_name: "prometheus"

  domain_state_bucket_region: "%{hiera('domain_state_bucket_region')}"
  domain_state_bucket_name: "%{hiera('domain_state_bucket_name')}"
  domain_state_bucket_is_encrypted: "%{hiera('domain_state_bucket_is_encrypted')}"
  domain_state_key: "%{hiera('domain_state_key')}"

  network_state_bucket_region: "%{hiera('network_state_bucket_region')}"
  network_state_bucket_name: "%{hiera('network_state_bucket_name')}"
  network_state_bucket_is_encrypted: "%{hiera('network_state_bucket_is_encrypted')}"
  network_state_key: "%{hiera('network_state_key')}"

backend_config:
  region: "%{hiera('registry_state_bucket_region')}"
  bucket: "%{hiera('registry_state_bucket_name')}"
  encrypt: "%{hiera('registry_state_bucket_is_encrypted')}"
  key: "%{hiera('registry_state_key')}"
